/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Suphple Docs",
  "description": "Documentation for Suphple Framework",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ]
  ],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/authentication/",
      "relativePath": "docs/v1/authentication/index.md",
      "key": "v-6c8d448c",
      "path": "/docs/v1/authentication/",
      "lastUpdated": "6/24/2021, 3:20:22 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/authorization/",
      "relativePath": "docs/v1/authorization/index.md",
      "key": "v-43ecff5c",
      "path": "/docs/v1/authorization/",
      "lastUpdated": "6/24/2021, 3:20:22 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/adapters/",
      "relativePath": "docs/v1/adapters/index.md",
      "key": "v-02801218",
      "path": "/docs/v1/adapters/",
      "lastUpdated": "6/24/2021, 3:20:22 PM"
    },
    {
      "title": "Anatomy of a Suphple module",
      "frontmatter": {},
      "regularPath": "/docs/v1/basics/",
      "relativePath": "docs/v1/basics/index.md",
      "key": "v-1f1d7c9c",
      "path": "/docs/v1/basics/",
      "headers": [
        {
          "level": 2,
          "title": "Anatomy of a Suphple module",
          "slug": "anatomy-of-a-suphple-module"
        },
        {
          "level": 2,
          "title": "Request lifecycle",
          "slug": "request-lifecycle"
        }
      ],
      "lastUpdated": "6/25/2021, 4:12:36 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/config/",
      "relativePath": "docs/v1/config/index.md",
      "key": "v-07fc9510",
      "path": "/docs/v1/config/",
      "lastUpdated": "6/24/2021, 3:20:22 PM"
    },
    {
      "title": "CONTAINERS",
      "frontmatter": {},
      "regularPath": "/docs/v1/container/",
      "relativePath": "docs/v1/container/index.md",
      "key": "v-5073c5dc",
      "path": "/docs/v1/container/",
      "lastUpdated": "6/24/2021, 3:20:22 PM"
    },
    {
      "title": "Services and controllers",
      "frontmatter": {},
      "regularPath": "/docs/v1/controllers/",
      "relativePath": "docs/v1/controllers/index.md",
      "key": "v-dcf7e948",
      "path": "/docs/v1/controllers/",
      "headers": [
        {
          "level": 2,
          "title": "Services and controllers",
          "slug": "services-and-controllers"
        }
      ],
      "lastUpdated": "6/25/2021, 4:12:36 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/contributing/",
      "relativePath": "docs/v1/contributing/index.md",
      "key": "v-08d6a228",
      "path": "/docs/v1/contributing/",
      "headers": [
        {
          "level": 2,
          "title": "",
          "slug": "-11"
        }
      ],
      "lastUpdated": "6/24/2021, 3:20:22 PM"
    },
    {
      "title": "Credits",
      "frontmatter": {},
      "regularPath": "/docs/v1/credits/",
      "relativePath": "docs/v1/credits/index.md",
      "key": "v-7fcb167c",
      "path": "/docs/v1/credits/",
      "lastUpdated": "6/25/2021, 4:12:36 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/database/",
      "relativePath": "docs/v1/database/index.md",
      "key": "v-9ada42f4",
      "path": "/docs/v1/database/",
      "lastUpdated": "6/24/2021, 3:20:22 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/error-handling/",
      "relativePath": "docs/v1/error-handling/index.md",
      "key": "v-7b74bfe8",
      "path": "/docs/v1/error-handling/",
      "lastUpdated": "6/24/2021, 3:20:22 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/events/",
      "relativePath": "docs/v1/events/index.md",
      "key": "v-3f34248a",
      "path": "/docs/v1/events/",
      "lastUpdated": "6/24/2021, 3:20:22 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/flows/",
      "relativePath": "docs/v1/flows/index.md",
      "key": "v-1d41a048",
      "path": "/docs/v1/flows/",
      "headers": [
        {
          "level": 2,
          "title": "",
          "slug": "-4"
        }
      ],
      "lastUpdated": "6/24/2021, 7:24:35 PM"
    },
    {
      "title": "Laravel inter-operability",
      "frontmatter": {},
      "regularPath": "/docs/v1/laravel-interop/",
      "relativePath": "docs/v1/laravel-interop/index.md",
      "key": "v-0a2fbec8",
      "path": "/docs/v1/laravel-interop/",
      "headers": [
        {
          "level": 2,
          "title": "The cheering news!",
          "slug": "the-cheering-news"
        },
        {
          "level": 2,
          "title": "The downer!",
          "slug": "the-downer"
        }
      ],
      "lastUpdated": "6/25/2021, 4:12:36 PM"
    },
    {
      "title": "MIDDLEWARE",
      "frontmatter": {},
      "regularPath": "/docs/v1/middleware/",
      "relativePath": "docs/v1/middleware/index.md",
      "key": "v-029208d8",
      "path": "/docs/v1/middleware/",
      "lastUpdated": "6/24/2021, 3:20:22 PM"
    },
    {
      "title": "Modules",
      "frontmatter": {},
      "regularPath": "/docs/v1/modules/",
      "relativePath": "docs/v1/modules/index.md",
      "key": "v-d1891448",
      "path": "/docs/v1/modules/",
      "headers": [
        {
          "level": 2,
          "title": "Preamble: The modular philosophy",
          "slug": "preamble-the-modular-philosophy"
        },
        {
          "level": 2,
          "title": "When to create a new module",
          "slug": "when-to-create-a-new-module"
        }
      ],
      "lastUpdated": "6/25/2021, 4:12:36 PM"
    },
    {
      "title": "Motivation",
      "frontmatter": {},
      "regularPath": "/docs/v1/motivation/",
      "relativePath": "docs/v1/motivation/index.md",
      "key": "v-78efa5d0",
      "path": "/docs/v1/motivation/",
      "headers": [
        {
          "level": 2,
          "title": "Motivation",
          "slug": "motivation"
        }
      ],
      "lastUpdated": "6/25/2021, 4:12:36 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/plugins/",
      "relativePath": "docs/v1/plugins/index.md",
      "key": "v-fa67c888",
      "path": "/docs/v1/plugins/",
      "lastUpdated": "6/24/2021, 3:20:22 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/queues/",
      "relativePath": "docs/v1/queues/index.md",
      "key": "v-26fe0e10",
      "path": "/docs/v1/queues/",
      "lastUpdated": "6/24/2021, 3:20:22 PM"
    },
    {
      "title": "Requests",
      "frontmatter": {},
      "regularPath": "/docs/v1/requests/",
      "relativePath": "docs/v1/requests/index.md",
      "key": "v-4faa6574",
      "path": "/docs/v1/requests/",
      "headers": [
        {
          "level": 2,
          "title": "Requests",
          "slug": "requests"
        }
      ],
      "lastUpdated": "6/25/2021, 4:12:36 PM"
    },
    {
      "title": "Requirements",
      "frontmatter": {},
      "regularPath": "/docs/v1/quick-start/",
      "relativePath": "docs/v1/quick-start/index.md",
      "key": "v-1b00b37c",
      "path": "/docs/v1/quick-start/",
      "headers": [
        {
          "level": 2,
          "title": "Requirements",
          "slug": "requirements"
        },
        {
          "level": 2,
          "title": "Installation",
          "slug": "installation"
        },
        {
          "level": 2,
          "title": "Your first request",
          "slug": "your-first-request"
        }
      ],
      "lastUpdated": "6/25/2021, 4:12:36 PM"
    },
    {
      "title": "Graphql clone",
      "frontmatter": {},
      "regularPath": "/docs/v1/roadmap/",
      "relativePath": "docs/v1/roadmap/index.md",
      "key": "v-7db1243c",
      "path": "/docs/v1/roadmap/",
      "headers": [
        {
          "level": 2,
          "title": "Graphql clone",
          "slug": "graphql-clone"
        },
        {
          "level": 2,
          "title": "Flows",
          "slug": "flows"
        },
        {
          "level": 2,
          "title": "Open API",
          "slug": "open-api"
        },
        {
          "level": 2,
          "title": "Integration",
          "slug": "integration"
        },
        {
          "level": 2,
          "title": "File Upload",
          "slug": "file-upload"
        },
        {
          "level": 2,
          "title": "Authentication",
          "slug": "authentication"
        },
        {
          "level": 2,
          "title": "Service and controllers",
          "slug": "service-and-controllers"
        },
        {
          "level": 2,
          "title": "Routing",
          "slug": "routing"
        }
      ],
      "lastUpdated": "6/25/2021, 4:12:36 PM"
    },
    {
      "title": "SERVICE PROVIDERS",
      "frontmatter": {},
      "regularPath": "/docs/v1/service-providers/",
      "relativePath": "docs/v1/service-providers/index.md",
      "key": "v-0a380b7c",
      "path": "/docs/v1/service-providers/",
      "headers": [
        {
          "level": 2,
          "title": "SERVICE PROVIDERS",
          "slug": "service-providers"
        }
      ],
      "lastUpdated": "6/25/2021, 4:12:36 PM"
    },
    {
      "title": "Routing",
      "frontmatter": {},
      "regularPath": "/docs/v1/routing/",
      "relativePath": "docs/v1/routing/index.md",
      "key": "v-419f0608",
      "path": "/docs/v1/routing/",
      "headers": [
        {
          "level": 2,
          "title": "Introduction",
          "slug": "introduction"
        },
        {
          "level": 2,
          "title": "Route collections",
          "slug": "route-collections"
        },
        {
          "level": 2,
          "title": "Defining paths",
          "slug": "defining-paths"
        },
        {
          "level": 2,
          "title": "Dynamic routes",
          "slug": "dynamic-routes"
        },
        {
          "level": 2,
          "title": "Hyphenated segments",
          "slug": "hyphenated-segments"
        },
        {
          "level": 2,
          "title": "Optional placeholders",
          "slug": "optional-placeholders"
        },
        {
          "level": 2,
          "title": "Request methods",
          "slug": "request-methods"
        },
        {
          "level": 2,
          "title": "Route prefixing",
          "slug": "route-prefixing"
        },
        {
          "level": 2,
          "title": "Route matching: a brief history",
          "slug": "route-matching-a-brief-history"
        },
        {
          "level": 2,
          "title": "Revisiting prefixes",
          "slug": "revisiting-prefixes"
        },
        {
          "level": 2,
          "title": "Canaries",
          "slug": "canaries"
        },
        {
          "level": 2,
          "title": "CANARIES AND FEATURE TOGGLING",
          "slug": "canaries-and-feature-toggling"
        }
      ],
      "lastUpdated": "6/25/2021, 4:12:36 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/testing/",
      "relativePath": "docs/v1/testing/index.md",
      "key": "v-1a863dbc",
      "path": "/docs/v1/testing/",
      "lastUpdated": "6/24/2021, 3:20:22 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/templating/",
      "relativePath": "docs/v1/templating/index.md",
      "key": "v-1f172d64",
      "path": "/docs/v1/templating/",
      "lastUpdated": "6/24/2021, 3:20:22 PM"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.jpg",
        "tagline": "Opinionated PHP framework for building performant, extensible, and testable web applications",
        "actionText": "Quick Start →",
        "actionLink": "/docs/v1/quick-start/",
        "features": [
          {
            "title": "Built for the architecturally inclined",
            "details": "Domain Driven Design? Modular-monoliths? Decoupled components? SOLID principles? Slim controllers? Service oriented architectures? If those terms appeal to you, you are at the right place!"
          },
          {
            "title": "Intuitive Design",
            "details": "Given a penchant for OOP, objects are preferred over strings in all cases (labelling, payloads/DTOs, routing), for instant recognition of its purpose and location. No includes, no folder scanning, no questionable instantiation (during booting or whenever) is done without your consent"
          },
          {
            "title": "Infinite flexibility",
            "details": "Every step of the core experience is both replaceable and configurable in order to maximize your comfort. No conventional assumptions are made regarding project's requirements"
          }
        ],
        "footer": "Made by Nmeri Alphonsus with ❤️"
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-5a55ed49",
      "path": "/",
      "headers": [
        {
          "level": 3,
          "title": "Sustainability",
          "slug": "sustainability"
        },
        {
          "level": 3,
          "title": "Closing remarks",
          "slug": "closing-remarks"
        }
      ],
      "lastUpdated": "6/25/2021, 4:12:36 PM"
    }
  ],
  "themeConfig": {
    "repo": "https://github.com/nmeri17/tilwa",
    "docsRepo": "https://github.com/nmeri17/suphple-docs",
    "editLinks": false,
    "docsDir": "",
    "editLinkText": "",
    "lastUpdated": true,
    "logo": "/logo.jpg",
    "searchPlaceholder": "Search topic",
    "base": "/suphple-docs/",
    "sidebarDepth": 2,
    "nav": [
      {
        "text": "Quick Start",
        "link": "/docs/v1/quick-start/"
      },
      {
        "text": "Motivation",
        "link": "/docs/v1/motivation/"
      }
    ],
    "sidebar": [
      [
        "/docs/v1/quick-start/",
        "Quick Start"
      ],
      [
        "/docs/v1/basics/",
        "Basics"
      ],
      [
        "/docs/v1/modules/",
        "Modules"
      ],
      [
        "/docs/v1/container/",
        "Container"
      ],
      [
        "/docs/v1/service-providers/",
        "Service Providers"
      ],
      [
        "/docs/v1/testing/",
        "Testing"
      ],
      [
        "/docs/v1/routing/",
        "Routing"
      ],
      [
        "/docs/v1/requests/",
        "Requests"
      ],
      [
        "/docs/v1/controllers/",
        "Controllers"
      ],
      [
        "/docs/v1/events/",
        "Events"
      ],
      [
        "/docs/v1/queues/",
        "Queues"
      ],
      [
        "/docs/v1/config/",
        "Config"
      ],
      [
        "/docs/v1/authentication/",
        "Authentication"
      ],
      [
        "/docs/v1/authorization/",
        "Authorization"
      ],
      [
        "/docs/v1/middleware/",
        "Middleware"
      ],
      [
        "/docs/v1/error-handling/",
        "Error Handling"
      ],
      [
        "/docs/v1/templating/",
        "Templating"
      ],
      [
        "/docs/v1/flows/",
        "Flows"
      ],
      [
        "/docs/v1/laravel-interop/",
        "Laravel Inter-op"
      ],
      [
        "/docs/v1/plugins/",
        "Plugins"
      ],
      [
        "/docs/v1/contributing/",
        "Contributing"
      ],
      [
        "/docs/v1/credits/",
        "Credits"
      ],
      [
        "/docs/v1/roadmap/",
        "Roadmap"
      ]
    ]
  }
}