/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Suphple Docs",
  "description": "Documentation for Suphple Framework",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ]
  ],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/adapters/",
      "relativePath": "docs/v1/adapters/index.md",
      "key": "v-02801218",
      "path": "/docs/v1/adapters/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/config/",
      "relativePath": "docs/v1/config/index.md",
      "key": "v-07fc9510",
      "path": "/docs/v1/config/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/authorization/",
      "relativePath": "docs/v1/authorization/index.md",
      "key": "v-43ecff5c",
      "path": "/docs/v1/authorization/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/authentication/",
      "relativePath": "docs/v1/authentication/index.md",
      "key": "v-6c8d448c",
      "path": "/docs/v1/authentication/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/container/",
      "relativePath": "docs/v1/container/index.md",
      "key": "v-5073c5dc",
      "path": "/docs/v1/container/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/controllers/",
      "relativePath": "docs/v1/controllers/index.md",
      "key": "v-dcf7e948",
      "path": "/docs/v1/controllers/"
    },
    {
      "title": "Basics...Anatomy of a tilwa app",
      "frontmatter": {},
      "regularPath": "/docs/v1/basics/",
      "relativePath": "docs/v1/basics/index.md",
      "key": "v-1f1d7c9c",
      "path": "/docs/v1/basics/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/credits/",
      "relativePath": "docs/v1/credits/index.md",
      "key": "v-7fcb167c",
      "path": "/docs/v1/credits/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/contributing/",
      "relativePath": "docs/v1/contributing/index.md",
      "key": "v-08d6a228",
      "path": "/docs/v1/contributing/",
      "headers": [
        {
          "level": 2,
          "title": "",
          "slug": "-11"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/database/",
      "relativePath": "docs/v1/database/index.md",
      "key": "v-9ada42f4",
      "path": "/docs/v1/database/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/events/",
      "relativePath": "docs/v1/events/index.md",
      "key": "v-3f34248a",
      "path": "/docs/v1/events/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/flows/",
      "relativePath": "docs/v1/flows/index.md",
      "key": "v-1d41a048",
      "path": "/docs/v1/flows/",
      "headers": [
        {
          "level": 2,
          "title": "",
          "slug": "-4"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/middleware/",
      "relativePath": "docs/v1/middleware/index.md",
      "key": "v-029208d8",
      "path": "/docs/v1/middleware/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/laravel-interop/",
      "relativePath": "docs/v1/laravel-interop/index.md",
      "key": "v-0a2fbec8",
      "path": "/docs/v1/laravel-interop/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/error-handling/",
      "relativePath": "docs/v1/error-handling/index.md",
      "key": "v-7b74bfe8",
      "path": "/docs/v1/error-handling/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/modules/",
      "relativePath": "docs/v1/modules/index.md",
      "key": "v-d1891448",
      "path": "/docs/v1/modules/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/motivation/",
      "relativePath": "docs/v1/motivation/index.md",
      "key": "v-78efa5d0",
      "path": "/docs/v1/motivation/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/queues/",
      "relativePath": "docs/v1/queues/index.md",
      "key": "v-26fe0e10",
      "path": "/docs/v1/queues/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/plugins/",
      "relativePath": "docs/v1/plugins/index.md",
      "key": "v-fa67c888",
      "path": "/docs/v1/plugins/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/service-providers/",
      "relativePath": "docs/v1/service-providers/index.md",
      "key": "v-0a380b7c",
      "path": "/docs/v1/service-providers/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/routing/",
      "relativePath": "docs/v1/routing/index.md",
      "key": "v-419f0608",
      "path": "/docs/v1/routing/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/quick-start/",
      "relativePath": "docs/v1/quick-start/index.md",
      "key": "v-1b00b37c",
      "path": "/docs/v1/quick-start/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/testing/",
      "relativePath": "docs/v1/testing/index.md",
      "key": "v-1a863dbc",
      "path": "/docs/v1/testing/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/templating/",
      "relativePath": "docs/v1/templating/index.md",
      "key": "v-1f172d64",
      "path": "/docs/v1/templating/"
    },
    {
      "frontmatter": {},
      "regularPath": "/docs/v1/requests/",
      "relativePath": "docs/v1/requests/index.md",
      "key": "v-4faa6574",
      "path": "/docs/v1/requests/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.jpg",
        "tagline": "Opinionated PHP framework for building performant, extensible, and testable web applications",
        "actionText": "Quick Start →",
        "actionLink": "/quick-start/",
        "footer": "Made by Nmeri Alphonsus with ❤️"
      },
      "regularPath": "/",
      "relativePath": "index.md",
      "key": "v-5a55ed49",
      "path": "/"
    }
  ],
  "themeConfig": {
    "repo": "https://github.com/nmeri17/tilwa",
    "docsRepo": "https://github.com/nmeri17/suphple-docs",
    "editLinks": false,
    "docsDir": "",
    "editLinkText": "",
    "lastUpdated": true,
    "logo": "logo.jpg",
    "nav": [
      {
        "text": "Quick Start",
        "link": "/docs/v1/quick-start/"
      },
      {
        "text": "Basics",
        "link": "/docs/v1/basics/"
      }
    ],
    "sidebar": [
      [
        "/docs/v1/quick-start/",
        "Quick Start"
      ],
      [
        "/docs/v1/basics/",
        "Basics"
      ],
      [
        "/docs/v1/motivation/",
        "Motivation"
      ],
      [
        "/docs/v1/modules/",
        "Modules"
      ],
      [
        "/docs/v1/container/",
        "Container"
      ],
      [
        "/docs/v1/service-providers/",
        "Service Providers"
      ],
      [
        "/docs/v1/testing/",
        "Testing"
      ],
      [
        "/docs/v1/routing/",
        "Routing"
      ],
      [
        "/docs/v1/requests/",
        "Requests"
      ],
      [
        "/docs/v1/controllers/",
        "Controllers"
      ],
      [
        "/docs/v1/events/",
        "Events"
      ],
      [
        "/docs/v1/queues/",
        "Queues"
      ],
      [
        "/docs/v1/config/",
        "Config"
      ],
      [
        "/docs/v1/authentication/",
        "Authentication"
      ],
      [
        "/docs/v1/authorization/",
        "Authorization"
      ],
      [
        "/docs/v1/middleware/",
        "Middleware"
      ],
      [
        "/docs/v1/error-handling/",
        "Error Handling"
      ],
      [
        "/docs/v1/templating/",
        "Templating"
      ],
      [
        "/docs/v1/flows/",
        "Flows"
      ],
      [
        "/docs/v1/laravel-interop/",
        "Laravel Inter-op"
      ],
      [
        "/docs/v1/plugins/",
        "Plugins"
      ],
      [
        "/docs/v1/contributing/",
        "Contributing"
      ],
      [
        "/docs/v1/credits/",
        "Credits"
      ]
    ]
  }
}